version: '3.5'

services:
  houndstooth:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    environment:
      - CI=true
      - NODE_ENV=test
      - CC_TEST_REPORTER_ID=dec90da3e45d065843a58d884cc1e155141a96c8c0298cb9cacf09e2f4965e16
      - GIT_COMMIT_SHA
      - GIT_BRANCH
